### ISSUE TITLE
How to be able to use the SASS indented syntax

### ISSUE THREAD

**Issue by wouter-muller** [nfplee/gulp-vue-single-file-component#8]
Hello :)

Is it possible to instead of using LESS (or CSS or SCSS) use the indented SASS syntax inside the `<style>` blocks inside a single-file component?

I noticed in the `gulpfile.js` there is this line:

`.pipe(vueComponent({ debug: true, loadCssMethod: "loadCss" }))`

And a function `loadCSS` inside `<head>` as per your example. 

So instead of this:
```
<style lang="scss">
.hello {
    color: red;

    span {
        color: blue;
    }
}
</style>
```
i would like to be able to use this:
```
<style lang="sass">
.hello 
    color: red

    span 
        color: blue
</style>
```
We use the SASS indented syntax in all our projects, so it would be a shame to have to use SCSS for just this 1 project.

Thank you!

**Comment by nfplee** [comment]
Just commenting to say I have noted this issue and I'll be looking into it when I get a chance.

**Comment by wouter-muller** [comment]
That would be amazing :)

**Comment by nfplee** [comment]
I've just had a quick look, are you sure this isn't already supported? Looking at the [options that are fed into the Sass compiler](https://github.com/nfplee/gulp-vue-single-file-component/blob/bf65d94d7d9135aab4bd65ab574b09ee90de1b1c/index.js#L70) it looks like it should work. Please let me know if there's any problems and I'll look into it further.

**Comment by wouter-muller** [comment]
Hmmm, that piece of code does look like it should work indeed, but when i tried it, it just compiled it as SCSS. But i'll try it again and see if maybe I did something wrong... Thanks!

**Comment by wouter-muller** [comment]
In the example project i changed:
```
<style lang="less">
.hello {
    color: red;

    span {
        color: blue;
    }
}
</style>
```
to
```
<style lang="sass">
.hello
    color: red

    span
        color: blue
</style>
```
I ran `gulp` and this is the output i get:
```
[13:02:22] 'vue' errored after 119 ms
[13:02:22] Error: Invalid CSS after ".": expected 1 selector or at-rule, was ".hello color: red s"
    at Object.module.exports.renderSync (/Users/woutermuller/projects/temp/vue-sfc/node_modules/node-sass/lib/index.js:440:23)
    at /Users/woutermuller/projects/temp/vue-sfc/node_modules/gulp-vue-single-file-component/index.js:79:39
    at Array.forEach (<anonymous>)
    at Transform._transform (/Users/woutermuller/projects/temp/vue-sfc/node_modules/gulp-vue-single-file-component/index.js:57:29)
    at Transform._read (/Users/woutermuller/projects/temp/vue-sfc/node_modules/gulp-vue-single-file-component/node_modules/readable-stream/lib/_stream_transform.js:177:10)
    at Transform._write (/Users/woutermuller/projects/temp/vue-sfc/node_modules/gulp-vue-single-file-component/node_modules/readable-stream/lib/_stream_transform.js:164:83)
    at doWrite (/Users/woutermuller/projects/temp/vue-sfc/node_modules/gulp-vue-single-file-component/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/Users/woutermuller/projects/temp/vue-sfc/node_modules/gulp-vue-single-file-component/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at Transform.Writable.write (/Users/woutermuller/projects/temp/vue-sfc/node_modules/gulp-vue-single-file-component/node_modules/readable-stream/lib/_stream_writable.js:307:11)
    at DestroyableTransform.ondata (/Users/woutermuller/projects/temp/vue-sfc/node_modules/readable-stream/lib/_stream_readable.js:619:20)
```
Also changed the number of spaces from 4 to 2, same result...

**Comment by nfplee** [comment]
There was a problem with it trying to minify the code which removed the spaces which should now be fixed. Please can you try again with the latest version.

**Comment by wouter-muller** [comment]
Works perfectly now :) thanks!
